package com.NadraWraper.API;

import com.NadraWraper.Service.ConsumerPinCreation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/consumer/pin")

public class PinController {

    @Autowired
private ConsumerPinCreation consumerPinCreation;


@PostMapping("/generate")
    public String generatePin(@RequestBody Map<String, String> request) {
        String cnic = request.get("userId");
        return consumerPinCreation.saveAutoGeneratedPin(cnic);
    }
@PostMapping("/get")
    public String getPin(@RequestBody Map<String, String> request) {
        String cnic = request.get("userId");
        return consumerPinCreation.getPin(cnic);
    }

}
